apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: matrix-stack
  namespace: pbs-matrix
spec:
  interval: 1h
  url: oci://ghcr.io/element-hq/ess-helm/matrix-stack
  ref:
    tag: 26.2.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ess
  namespace: pbs-matrix
spec:
  serviceAccountName: pbs-matrix
  interval: 10m0s
  chartRef:
    name: matrix-stack
    namespace: pbs-matrix
    kind: OCIRepository
  values:
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure # necessary, since we have multiple entrypoints
    elementAdmin:
      ingress:
        host: admin.chat.tractor.scout.ch
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
    elementWeb:
      ingress:
        host: chat.tractor.scout.ch
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
    matrixAuthenticationService:
      postgres:
        host: postgres.tractor.scout.ch
        port: 5432
        user: pbs-matrix-authentication-service
        password:
          secret: pbs-matrix-authentication-service-postgres
          secretKey: password
        database: pbs-matrix-authentication-service
        sslMode: prefer
      ingress:
        host: account.chat.tractor.scout.ch
      additional:
        secrets.yaml:
          configSecret: pbs-matrix-authentication-service-upstream-oauth2
          configSecretKey: upstream_oauth2
        auth.yaml:
          config: |
            account:
              email_change_allowed: false
              displayname_change_allowed: true
            passwords:
              enabled: false
        email.yaml:
          config: |
            email:
              from: '"chat.tractor.scout.ch Auth Service" <no-reply@chat.tractor.scout.ch>'
              reply_to: '"Nicolas Da Mutten / Clever" <nicolas.damutten@pbs.ch>'
              transport: smtp
              mode: tls
              hostname: smtp.mailomat.cloud
              port: 587
              username: no-reply@chat.tractor.scout.ch
        email-secret.yaml:
          configSecret: pbs-matrix-authentication-service-email
          configSecretKey: config
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
    matrixRTC:
      ingress:
        host: mrtc.chat.tractor.scout.ch
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      sfu:
        nodeSelector:
          kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
        manualIP: 37.156.43.151
        useStunToDiscoverPublicIP: false
        exposedServices:
          rtcTcp:
            portType: HostPort
          rtcMuxedUdp:
            portType: HostPort
    serverName: chat.tractor.scout.ch
    synapse:
      additional:
        user-directory.yaml:
          config: |
            user_directory:
              enabled: true
              search_all_users: true
              prefer_local_users: true
            room_list_publication_rules:
              - action: allow
            alias_creation_rules:
              - action: allow
        email.yaml:
          config: |
            email:
              smtp_host: smtp.mailomat.cloud
              smtp_port: 587
              smtp_user: "no-reply@chat.tractor.scout.ch"
              force_tls: true
              notif_from: "chat.tractor.scout.ch <no-reply@chat.tractor.scout.ch>"
              app_name: "chat.tractor.scout.ch"
              enable_notifs: true
              notif_for_new_users: false
        email-secret.yaml:
          configSecret: pbs-matrix-synapse-email
          configSecretKey: config
      postgres:
        host: postgres.tractor.scout.ch
        port: 5432
        user: pbs-matrix
        password:
          secret: pbs-matrix-postgres
          secretKey: password
        database: pbs-matrix
        sslMode: prefer
      ingress:
        host: matrix.chat.tractor.scout.ch
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      media:
        storage:
          resourcePolicy: delete
          storageClassName: csi-cinder-sc-delete
    initSecrets:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
    deploymentMarkers:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
    haproxy:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
    postgres:
      enabled: false
    wellKnownDelegation:
      baseDomainRedirect:
        enabled: false
    certManager:
      clusterIssuer: letsencrypt
